Add tr() to visible strings
hteso/iaito pull request #209
Opened 2017-09-07 22:45 UTC by iwiwsb

I changed every user-visible `"string"` to `tr("string")` or to `QObject::tr("string")`. Hope I haven't missed any.

2017-09-08 01:00 UTC, xarkes commented
Hmmm it seems Travis build is broken. Also if you did them all, add "Fix #xxx" to your commit with XXX referencing the issue talking with tr.

2017-09-08 07:42 UTC, iwiwsb commented
Done. Sorry for so many title changes.

2017-09-08 17:35 UTC, xarkes commented
It does not compile on my machine:
```
mainwindow.cpp:370:84: error: no matching function for call to ‘MainWindow::tr(const QString)’
                              "\n" + core->cmd("ie") + "\n" + core->cmd("iM") + "\n"));
```
```
mainwindow.cpp:943:67: error: cannot convert ‘QString’ to ‘const char*’ for argument ‘1’ to ‘int printf(const char*, ...)’
     printf(tr("debug output: %s\n"), msg.toLocal8Bit().constData());
```

2017-09-08 17:42 UTC, xarkes requested changes
Please fix this

2017-09-08 17:42 UTC, xarkes commented on src/mainwindow.cpp
> +    printf(tr("debug output: %s\n"), msg.toLocal8Bit().constData());
No need to translate this debug message.

2017-09-08 17:42 UTC, xarkes commented on src/mainwindow.cpp
> +    qDebug() << tr("Meow: ") + fileName;
No need to translate.

2017-09-08 17:42 UTC, xarkes commented on src/qrdisasm.cpp
> +    printf(QObject::tr("FUCK\n"));
No need to translate.

2017-09-08 17:42 UTC, xarkes commented on src/createnewdialog.cpp
> +        __alert(tr("C Code: TODO"));
No need to translate a TODO message

2017-09-08 17:42 UTC, xarkes commented on src/createnewdialog.cpp
> +                __alert(tr("failed to open file"));
Missing capital letter

2017-09-08 17:42 UTC, xarkes commented on src/createnewdialog.cpp
> +                __alert(tr("failed to open file"));
Capital F

2017-09-08 17:42 UTC, xarkes commented on src/createnewdialog.cpp
> +        __alert(tr("TODO: non-raw fileformat is not yet supported"));
No need to translate TODO

2017-09-09 09:35 UTC, xarkes commented
Cool thanks

2017-09-09 09:36 UTC, merged